name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Install Make
      run: sudo apt-get install -y make

    - name: Run tests
      run: |
        chmod +x test_script.sh
        ./test_script.sh
