name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Install Make
      run: sudo apt-get install -y make

    - name: Build and Run Tests
      run: |
          gcc main.c -o aco_program -lm
          echo "Test case 1:"
          echo -e "kota_05.csv\nMakassar\n" | ./aco_program
          echo "Test case 2:"
          echo -e "kota_16.csv\nJayapura\n" | ./aco_program
