name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C/C++ environment
      uses: actions/setup-environment@v1
      with:
        compiler: gcc

    - name: Run tests
      run: |
        chmod +x test_script.sh
        ./test_script.sh
