name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Install Make
      run: sudo apt-get install -y make

    - name: Build and Run Tests
      run: |
          gcc main.c -o aco_program -lm
          echo "Test case 1:"
          echo -e "kota_05.csv\nMakassar\n" | ./aco_program
          echo "Test case 2:"
          echo -e "kota_06.csv\nMakassar\n" | ./aco_program
          echo "Test case 3:"
          echo -e "kota_07.csv\nMakassar\n" | ./aco_program
          echo "Test case 4:"
          echo -e "kota_08.csv\nMakassar\n" | ./aco_program
          echo "Test case 5:"
          echo -e "kota_09.csv\nMakassar\n" | ./aco_program
          echo "Test case 6:"
          echo -e "kota_10.csv\nMakassar\n" | ./aco_program
          echo "Test case 7:"
          echo -e "kota_11.csv\nMakassar\n" | ./aco_program
          echo "Test case 8:"
          echo -e "kota_12.csv\nMakassar\n" | ./aco_program
          echo "Test case 9:"
          echo -e "kota_13.csv\nMakassar\n" | ./aco_program
          echo "Test case 10:"
          echo -e "kota_14.csv\nMakassar\n" | ./aco_program
          echo "Test case 11:"
          echo -e "kota_15.csv\nMakassar\n" | ./aco_program
          echo "Test case 12:"
          echo -e "kota_16.csv\nMakassar\n" | ./aco_program
